import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavMenu from "./NavMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="zh-hant">
			<head>
				<link rel="icon" type="image/svg+xml" href="/vite.svg" />
			</head>
			<body className={inter.className}>
				<header style={{ backgroundColor: 'lightblue', padding: '1rem' }}>
					<p>Header</p>
				</header>
				<NavMenu />
				<main>
						{children}
				</main>
				<footer style={{ backgroundColor: 'ghostwhite', padding: '1rem', color: 'darkgrey' }}>
					<p>Footer</p>
				</footer>
			</body>
		</html>
	);
}
